-- ---------------------------------------------------------------------------
-- Kuwaiti Oil Tankers — relational schema
--
-- A fleet register for the Kuwait Oil Tanker Company (KOTC), the tanker arm of
-- Kuwait Petroleum Corporation, together with the ports and cargo grades it
-- trades and a voyage table to join them.
--
-- Portable ANSI-ish DDL: runs unchanged on SQLite 3.25+ and PostgreSQL 12+.
-- On SQLite, enable foreign keys first:  PRAGMA foreign_keys = ON;
--
-- PROVENANCE. Four of the five tables hold real, sourced data. The fifth,
-- `voyages`, is SYNTHETIC — generated by build.py from a fixed seed so the
-- schema has something to join against. No row in `voyages` describes a real
-- shipment. Every row carries data_source = 'synthetic' to keep that visible
-- in any query result. See README.md.
-- ---------------------------------------------------------------------------

DROP VIEW  IF EXISTS v_trade_lanes;
DROP VIEW  IF EXISTS v_vessel_utilisation;
DROP VIEW  IF EXISTS v_fleet_summary;
DROP TABLE IF EXISTS voyages;
DROP TABLE IF EXISTS vessels;
DROP TABLE IF EXISTS builders;
DROP TABLE IF EXISTS cargo_types;
DROP TABLE IF EXISTS ports;


-- Shipyards that built the fleet. Derived from vessels.csv by build.py.
CREATE TABLE builders (
  builder_id    TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  country       TEXT
);


-- Loading terminals in Kuwait and the discharge ports the fleet serves.
CREATE TABLE ports (
  port_id                        TEXT PRIMARY KEY,
  name                           TEXT NOT NULL,
  name_ar                        TEXT,
  country                        TEXT NOT NULL,
  country_iso2                   CHAR(2) NOT NULL,
  region                         TEXT,
  -- Approximate anchor coordinates for the port area, not a berth position.
  latitude                       REAL,
  longitude                      REAL,
  role                           TEXT NOT NULL
                                   CHECK (role IN ('load','discharge','bunker')),
  -- Approximate sea distance from Mina Al-Ahmadi, nautical miles. Indicative
  -- routeing figures, not a published distance table.
  sea_distance_from_ahmadi_nm    INTEGER
                                   CHECK (sea_distance_from_ahmadi_nm >= 0),
  notes                          TEXT
);


-- Crude grades, refined products and gases the fleet lifts.
CREATE TABLE cargo_types (
  cargo_code       TEXT PRIMARY KEY,
  name             TEXT NOT NULL,
  category         TEXT NOT NULL
                     CHECK (category IN ('crude','product','lpg')),
  -- Nominal assay values for the crude grades; approximate and published
  -- figures vary between cargoes. NULL for products and gases.
  api_gravity      REAL CHECK (api_gravity IS NULL OR api_gravity BETWEEN 5 AND 70),
  sulphur_pct      REAL CHECK (sulphur_pct IS NULL OR sulphur_pct BETWEEN 0 AND 10),
  typical_carrier  TEXT,
  notes            TEXT
);


-- The fleet register. One row per vessel.
CREATE TABLE vessels (
  vessel_id        TEXT PRIMARY KEY,
  name             TEXT NOT NULL,
  name_ar          TEXT,
  -- IMO numbers are permanent and unique to a hull; they survive renaming.
  imo              INTEGER NOT NULL UNIQUE
                     CHECK (imo BETWEEN 1000000 AND 9999999),
  -- MMSI is tied to the current registration, so it changes when a ship
  -- reflags. Where it disagrees with the recorded flag, status says so.
  mmsi             INTEGER,
  call_sign        TEXT,
  vessel_type      TEXT NOT NULL
                     CHECK (vessel_type IN ('VLCC','Aframax','MR Product Tanker',
                                            'VLGC','LPG Carrier','Bunker Vessel')),
  cargo_class      TEXT NOT NULL
                     CHECK (cargo_class IN ('crude','products','lpg','bunkers')),
  dwt              INTEGER CHECK (dwt IS NULL OR dwt > 0),
  -- How the deadweight figure was obtained: 'reported' for a figure published
  -- for this hull, 'sister_vessel_class' where it is carried across from a
  -- confirmed sister in the same series.
  dwt_basis        TEXT CHECK (dwt_basis IS NULL OR
                               dwt_basis IN ('reported','sister_vessel_class')),
  capacity_cbm     INTEGER CHECK (capacity_cbm IS NULL OR capacity_cbm > 0),
  loa_m            REAL CHECK (loa_m IS NULL OR loa_m > 0),
  beam_m           REAL CHECK (beam_m IS NULL OR beam_m > 0),
  built_year       INTEGER NOT NULL CHECK (built_year BETWEEN 1950 AND 2100),
  builder_id       TEXT REFERENCES builders (builder_id),
  builder          TEXT,
  builder_country  TEXT,
  flag             TEXT,
  operator         TEXT NOT NULL,
  status           TEXT NOT NULL
                     CHECK (status IN ('in_service','flag_unverified','laid_up','sold','scrapped')),
  notes            TEXT,
  -- A gas carrier is the only thing that should carry a cubic capacity.
  CHECK (capacity_cbm IS NULL OR cargo_class = 'lpg'),
  -- A deadweight figure must say where it came from, and vice versa.
  CHECK ((dwt IS NULL) = (dwt_basis IS NULL))
);

CREATE INDEX idx_vessels_type       ON vessels (vessel_type);
CREATE INDEX idx_vessels_cargo      ON vessels (cargo_class);
CREATE INDEX idx_vessels_built_year ON vessels (built_year);
CREATE INDEX idx_vessels_builder    ON vessels (builder_id);


-- SYNTHETIC. Generated voyages, present so the register can be queried as a
-- fleet rather than read as a list. Not a record of real shipments.
CREATE TABLE voyages (
  voyage_id           TEXT PRIMARY KEY,
  vessel_id           TEXT NOT NULL REFERENCES vessels (vessel_id),
  load_port_id        TEXT NOT NULL REFERENCES ports (port_id),
  discharge_port_id   TEXT NOT NULL REFERENCES ports (port_id),
  cargo_code          TEXT NOT NULL REFERENCES cargo_types (cargo_code),
  departure_date      DATE NOT NULL,
  arrival_date        DATE NOT NULL,
  sea_days            INTEGER NOT NULL CHECK (sea_days > 0),
  distance_nm         INTEGER NOT NULL CHECK (distance_nm > 0),
  laden_speed_knots   REAL    NOT NULL CHECK (laden_speed_knots BETWEEN 5 AND 25),
  cargo_tonnes        INTEGER NOT NULL CHECK (cargo_tonnes > 0),
  -- Freight expressed in Worldscale points, the tanker market's rate unit.
  freight_rate_ws     REAL    CHECK (freight_rate_ws > 0),
  data_source         TEXT    NOT NULL DEFAULT 'synthetic'
                        CHECK (data_source = 'synthetic'),
  CHECK (arrival_date > departure_date),
  CHECK (load_port_id <> discharge_port_id)
);

CREATE INDEX idx_voyages_vessel    ON voyages (vessel_id);
CREATE INDEX idx_voyages_discharge ON voyages (discharge_port_id);
CREATE INDEX idx_voyages_cargo     ON voyages (cargo_code);
CREATE INDEX idx_voyages_departure ON voyages (departure_date);


-- --------------------------------------------------------------------------
-- Views
-- --------------------------------------------------------------------------

-- The fleet at a glance: how many hulls of each type, how much they lift, and
-- how old they are. Reads real data only. Ages are measured against REFERENCE_YEAR
-- below; bump it when the dataset is refreshed.
CREATE VIEW v_fleet_summary AS
SELECT
  vessel_type,
  cargo_class,
  COUNT(*)                        AS vessel_count,
  SUM(dwt)                        AS total_dwt,
  ROUND(AVG(dwt))                 AS avg_dwt,
  MIN(built_year)                 AS oldest_built,
  MAX(built_year)                 AS newest_built,
  ROUND(AVG(2026 - built_year), 1) AS avg_age_years  -- REFERENCE_YEAR = 2026
FROM vessels
GROUP BY vessel_type, cargo_class;


-- Per-vessel activity over the synthetic voyage set.
CREATE VIEW v_vessel_utilisation AS
SELECT
  v.vessel_id,
  v.name,
  v.vessel_type,
  v.dwt,
  COUNT(y.voyage_id)                       AS voyages,
  SUM(y.cargo_tonnes)                      AS tonnes_carried,
  SUM(y.sea_days)                          AS laden_sea_days,
  SUM(y.distance_nm)                       AS laden_distance_nm,
  ROUND(CAST(AVG(y.laden_speed_knots) AS NUMERIC), 2) AS avg_laden_speed_knots
FROM vessels v
LEFT JOIN voyages y ON y.vessel_id = v.vessel_id
GROUP BY v.vessel_id, v.name, v.vessel_type, v.dwt;


-- Where the cargo goes, over the synthetic voyage set.
CREATE VIEW v_trade_lanes AS
SELECT
  lp.name                    AS load_port,
  dp.name                    AS discharge_port,
  dp.country                 AS discharge_country,
  dp.region                  AS discharge_region,
  c.category                 AS cargo_category,
  COUNT(*)                   AS voyages,
  SUM(y.cargo_tonnes)        AS tonnes,
  ROUND(AVG(y.sea_days), 1)  AS avg_sea_days
FROM voyages y
JOIN ports       lp ON lp.port_id    = y.load_port_id
JOIN ports       dp ON dp.port_id    = y.discharge_port_id
JOIN cargo_types c  ON c.cargo_code  = y.cargo_code
GROUP BY lp.name, dp.name, dp.country, dp.region, c.category;
